dist: trusty
language: java

addons:
  sonarcloud:
    organization: "damaya0226"

script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=kalah-api
  - docker build -t damaya0226/kalah-api .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push damaya0226/kalah-api